version: '3.7'
services:
  db:
    image: mysql:latest
    env_file:
      - ./.env
    ports:
      - "3307:3306"
    networks:
      - pma_net
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  pma:
    image: phpmyadmin:latest
    env_file:
      - ./.env
    ports:
      - "88:80"   
    networks:
      - pma_net
    depends_on:
      - db
networks:
  pma_net: