CREATE TABLE quotes (
    id int(8) PRIMARY KEY AUTO_INCREMENT,
    author varchar(255),
    quote varchar(255)
);

INSERT INTO quotes (author, quote) VALUES
('Walt Disney', 'The way to get started is to quit talking and begin doing.'),
('Nelson Mandela', 'The greatest glory in living lies not in never falling, but in rising every time we fall.'),
('Steve Jobs', 'Your time is limited, don\'t waste it living someone else\'s life.'),
('Albert Einstein', 'Imagination is more important than knowledge.'),
('Mahatma Gandhi', 'Be the change that you wish to see in the world.'),
('Mark Twain', 'The secret of getting ahead is getting started.'),
('Dr. Seuss', 'You know you\'re in love when you can\'t fall asleep because reality is finally better than your dreams.'),
('Oprah Winfrey', 'Turn your wounds into wisdom.'),
('Helen Keller', 'The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.'),
('Winston Churchill', 'Success is not final, failure is not fatal: It is the courage to continue that counts.'),
('Abraham Lincoln', 'In the end, it\'s not the years in your life that count. It\'s the life in your years.'),
('Martin Luther King Jr.', 'Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.'),
('Maya Angelou', 'I\'ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.'),
('Eleanor Roosevelt', 'No one can make you feel inferior without your consent.'),
('John Lennon', 'Life is what happens when you\'re busy making other plans.'),
('Jordan Belfort', 'The only thing standing between you and your goal is the story you keep telling yourself as to why you can\'t achieve it.'),
('Roy T. Bennett', 'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.'),
('Thomas A. Edison', 'I have not failed. I\'ve just found 10,000 ways that won\'t work.'),
('Franklin D. Roosevelt', 'The only limit to our realization of tomorrow will be our doubts of today.'),
('Albert Schweitzer', 'Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.'),
('Zig Ziglar', 'You don\'t have to be great to start, but you have to start to be great.'),
('Anonymous', 'The only person you should try to be better than is the person you were yesterday.'),
('Norman Vaughan', 'Dream big and dare to fail.'),
('Bo Bennett', 'Success is not in what you have, but who you are.'),
('Muhammad Ali', 'Don\'t count the days, make the days count.'),
('Socrates', 'The only true wisdom is in knowing you know nothing.'),
('Frank Sinatra', 'The best revenge is massive success.'),
('C.S. Lewis', 'You are never too old to set another goal or to dream a new dream.'),
('Pablo Picasso', 'Everything you can imagine is real.'),
('Jimmy Dean', 'I can\'t change the direction of the wind, but I can adjust my sails to always reach my destination.'),
('Mark Zuckerberg', 'The biggest risk is not taking any risk. In a world that\'s changing really quickly, the only strategy that is guaranteed to fail is not taking risks.'),
('Ralph Waldo Emerson', 'Do not go where the path may lead, go instead where there is no path and leave a trail.'),
('Henry Ford', 'Whether you think you can or you think you can\'t, you\'re right.'),
('Steve Jobs', 'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.'),
('Helen Keller', 'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.'),
('J.K. Rowling', 'It is our choices, Harry, that show what we truly are, far more than our abilities.'),
('Napoleon Hill', 'Don\'t wait. The time will never be just right.'),
('Thomas Edison', 'Many of life\'s failures are people who did not realize how close they were to success when they gave up.'),
('Rumi', 'The wound is the place where the light enters you.'),
('Bruce Lee', 'I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.'),
('Babe Ruth', 'Never let the fear of striking out keep you from playing the game.'),
('Coco Chanel', 'The most courageous act is still to think for yourself. Aloud.'),
('William Shakespeare', 'We know what we are, but know not what we may be.'),
('Elon Musk', 'When something is important enough, you do it even if the odds are not in your favor.'),
('Hermann Hesse', 'Some of us think holding on makes us strong, but sometimes it is letting go.'),
('Vincent Van Gogh', 'I dream my painting and I paint my dream.'),
('Confucius', 'It does not matter how slowly you go as long as you do not stop.'),
('Peter Drucker', 'The best way to predict the future is to create it.'),
('Chantal Sutherland', 'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.'),
('John Wooden', 'Do not let what you cannot do interfere with what you can do.'),
('Vidal Sassoon', 'The only place where success comes before work is in the dictionary.'),
('Ralph Waldo Emerson', 'What lies behind us and what lies before us are tiny matters compared to what lies within us.'),
('Confucius', 'It does not matter how slowly you go as long as you do not stop.'),
('Peter Drucker', 'The best way to predict the future is to create it.'),
('Chantal Sutherland', 'Believe in yourself, take on your challenges, dig deep within yourself to conquer fears. Never let anyone bring you down. You got this.'),
('John Wooden', 'Do not let what you cannot do interfere with what you can do.'),
('Vidal Sassoon', 'The only place where success comes before work is in the dictionary.'),
('Zig Ziglar', 'If you can dream it, you can achieve it.'),
('Sam Levenson', 'Don\'t watch the clock; do what it does. Keep going.'),
('Eleanor Roosevelt', 'The future belongs to those who believe in the beauty of their dreams.'),
('Franklin D. Roosevelt', 'The only limit to our realization of tomorrow will be our doubts of today.'),
('George Washington', 'The harder the conflict, the greater the triumph.'),
('Henry David Thoreau', 'Success usually comes to those who are too busy to be looking for it.'),
('Thomas Jefferson', 'I find that the harder I work, the more luck I seem to have.'),
('Stephen Covey', 'I am not a product of my circumstances. I am a product of my decisions.'),
('Henry Ford', 'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.'),
('George S. Patton', 'Accept the challenges so that you can feel the exhilaration of victory.'),
('George Bernard Shaw', 'Success does not consist in never making mistakes but in never making the same one a second time.'),
('Confucius', 'Our greatest glory is not in never falling, but in rising every time we fall.'),
('Jim Rohn', 'If you are not willing to risk the usual, you will have to settle for the ordinary.'),
('Anne Frank', 'How wonderful it is that nobody need wait a single moment before starting to improve the world.'),
('Aristotle', 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.'),
('Helen Keller', 'Life is either a daring adventure or nothing at all.'),
('Henry David Thoreau', 'Go confidently in the direction of your dreams. Live the life you have imagined.'),
('Oprah Winfrey', 'The biggest adventure you can take is to live the life of your dreams.'),
('Eleanor Roosevelt', 'Great minds discuss ideas; average minds discuss events; small minds discuss people.'),
('Ralph Waldo Emerson', 'The only person you are destined to become is the person you decide to be.'),
('Walt Disney', 'All our dreams can come true if we have the courage to pursue them.'),
('Mark Twain', 'Twenty years from now you will be more disappointed by the things that you didn\'t do than by the ones you did do.'),
('Maya Angelou', 'You may not control all the events that happen to you, but you can decide not to be reduced by them.'),
('Nelson Mandela', 'It always seems impossible until it\'s done.');